### ISSUE TITLE
blender integration macosX

### ISSUE THREAD

**Issue by fcollman** [navis-org/navis#62]
I installed a fresh anaconda environment python==3.9.2 on max os 11.6 "Big Sur" and then pip install navis into that environment.  I then symlinked the conda environment into the location that blender 2.93.5 had for its python path (moving the old one to a backup location). 

After starting blender I was able to import pandas, numpy and other packages I installed in the conda environment, but when trying to import navis i got the following error.

```PYTHON INTERACTIVE CONSOLE 3.9.2 (default, Mar 16 2021, 14:53:03)  [Clang 10.0.0 (clang-1000.11.45.5)]

Builtin Modules:       bpy, bpy.data, bpy.ops, bpy.props, bpy.types, bpy.context, bpy.utils, bgl, blf, mathutils
Convenience Imports:   from mathutils import *; from math import *
Convenience Variables: C = bpy.context, D = bpy.data

>>> import navis
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/navis/__init__.py", line 26, in <module>
    from .plotting import *
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/navis/plotting/__init__.py", line 15, in <module>
    from .dd import *
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/navis/plotting/dd.py", line 38, in <module>
    from .plot_utils import segments_to_coords, tn_pairs_to_coords
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/navis/plotting/plot_utils.py", line 32, in <module>
    from vispy.util.transforms import rotate
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/vispy/__init__.py", line 27, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/vispy/util/fonts/_triage.py", line 14, in <module>
    from ._quartz import _load_glyph, _list_fonts
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/vispy/util/fonts/_quartz.py", line 12, in <module>
    from ...ext.cocoapy import cf, ct, quartz, CFRange, CFSTR, CGGlyph, UniChar, \
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/vispy/ext/cocoapy.py", line 1288, in <module>
    quartz = cdll.LoadLibrary(util.find_library('quartz'))
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/ctypes/__init__.py", line 460, in LoadLibrary
    return self._dlltype(name)
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/ctypes/__init__.py", line 382, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(Quartz.framework/Quartz, 6): no suitable image found.  Did find:
    file system relative paths not allowed in hardened programs
```

I'm gonna try doing it the way you suggested in the documentation, but being able to use anaconda to install packages feels quite painful to me for many things, and it would be great to have a fully functional conda environment that could also work with blender.

**Comment by fcollman** [comment]
following the instructions to install navis in the shipped python environment (which is now 3.9.2 it seems with the latest blender), I get a similar but slightly different error.

```
PYTHON INTERACTIVE CONSOLE 3.9.2 (default, Mar 16 2021, 14:53:03)  [Clang 10.0.0 (clang-1000.11.45.5)]

Builtin Modules:       bpy, bpy.data, bpy.ops, bpy.props, bpy.types, bpy.context, bpy.utils, bgl, blf, mathutils
Convenience Imports:   from mathutils import *; from math import *
Convenience Variables: C = bpy.context, D = bpy.data

>>> import navis
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/navis/__init__.py", line 26, in <module>
    from .plotting import *
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/navis/plotting/__init__.py", line 15, in <module>
    from .dd import *
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/navis/plotting/dd.py", line 38, in <module>
    from .plot_utils import segments_to_coords, tn_pairs_to_coords
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/navis/plotting/plot_utils.py", line 32, in <module>
    from vispy.util.transforms import rotate
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/vispy/__init__.py", line 27, in <module>
    from .util import config, set_log_level, keys, sys_info  # noqa
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/vispy/util/__init__.py", line 14, in <module>
    from . import fonts       # noqa
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/vispy/util/fonts/__init__.py", line 13, in <module>
    from ._triage import _load_glyph, list_fonts  # noqa, analysis:ignore
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/vispy/util/fonts/_triage.py", line 14, in <module>
    from ._quartz import _load_glyph, _list_fonts
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/vispy/util/fonts/_quartz.py", line 12, in <module>
    from ...ext.cocoapy import cf, ct, quartz, CFRange, CFSTR, CGGlyph, UniChar, \
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/vispy/ext/cocoapy.py", line 946, in <module>
    cf = cdll.LoadLibrary(util.find_library('CoreFoundation'))
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(CoreFoundation.framework/CoreFoundation, 6): no suitable image found.  Did find:
    file system relative paths not allowed in hardened programs
```

**Comment by fcollman** [comment]
for now i hacked together a solution commenting out the 

```
from plotting import * 
```
from __init__.py and then somehow i can 

```
import navis.interfaces.blender as b3d
```
if i do it twice.. and then the example neuron can be added.

not sure why this all is... was going to upgrade my os x version anyway and we'll see what happens.

**Comment by schlegelp** [comment]
I have no experience trying to setup a conda environment in Blender. I'm actually rather surprised you got as far as you did. The problem appears to be with `vispy` but I have never seen that error before? What OS version/chip are you running?

**Comment by schlegelp** [comment]
What you could try is mocking `vispy`. See my response [here](https://github.com/navis-org/navis/issues/17#issuecomment-762123326)

**Comment by schlegelp** [comment]
Ah right - also just realised that you had mentioned Big Sur. Out of curiosity is it an M1?

**Comment by fcollman** [comment]
no this is an intel one.. i have a m1 laptop soon though, so i'll report when i find out.

**Comment by fcollman** [comment]
well upgrading to Monterey 12.0.1 simply fixed this issue.. didn't even have to reinstall anaconda or packages or anything. I'll close this issue but hopefully it will help others who might still be on BigSur
