### ISSUE TITLE
Neuromorpho neuron fetch

### ISSUE THREAD

**Issue by psynaptix1** [navis-org/navis#73]
When using NAVis integrated in Blender, I tried to fetch a neuron from the neuromorpho repository in the following way:
``` python
import navis
import navis.interfaces.blender as b3d
from navis.interfaces import neuromorpho as nmc

nl = nmc.get_neuron('Fig2a_cell1_1112071rm')
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\navis\interfaces\neuromorpho.py", line 187, in get_neuron
    n = read_swc(url, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\navis\io\swc_io.py", line 322, in read_swc
    return reader.read_any(f, include_subdirs, parallel)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\navis\io\base.py", line 646, in read_any
    return self.read_any_single(obj, attrs)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\navis\io\base.py", line 544, in read_any_single
    return self.read_url(obj, attrs)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\navis\io\base.py", line 445, in read_url
    return self.read_buffer(
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\navis\io\swc_io.py", line 101, in read_buffer
    header_rows = read_header_rows(f)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\navis\io\swc_io.py", line 222, in read_header_rows
    f.seek(0)
io.UnsupportedOperation: underlying stream is not seekable
```

Fetching neuron info via ```navis.interfaces.neuromorpho.get_neuron_info(x) ```  works fine.

**Comment by schlegelp** [comment]
I just pushed a fix for this to Github. Because I didn't bump the version you need to update by un- and then reinstalling `navis`. So in your case with Blender something like this:

```bash
$ /path/to/blender/python -m pip uninstall navis
$ /path/to/blender/python -m pip install git+git://github.com/navis-org/navis@master
```
